### ISSUE TITLE
Uncaught TypeError in latest Chrome while accessing error.stack

### ISSUE THREAD

**Issue by uiteoi** [evanw/node-source-map-support#167]
This was working very well until version 0.4.8.

After upgrading to version 0.4.9, I get in the console:
```
Uncaught TypeError
(anonymous)	@	browser-source-map-support.js.min:107
(anonymous)	@	browser-source-map-support.js.min:101
(anonymous)	@	browser-source-map-support.js.min:107
(anonymous)	@	browser-source-map-support.js.min:101
a	@	browser-source-map-support.js.min:101
b	@	browser-source-map-support.js.min:104
(anonymous)	@	browser-source-map-support.js.min:105
f	@	browser-source-map-support.js.min:105
i	@	pipelet.js:4203
```

The code in pipelet.js triggering this is:
```javascript
      try {
        throw new Error( '' );
      } catch( e ) {
        var stack = e.stack // this is line 4203 in pipelet.js
        // use stack
      }
```

**Comment by LinusU** [comment]
Hmm, this was probably #159 then, @kpdecker any ideas? :)

**Comment by ardeois** [comment]
I have the same issue. It looks like this is due to "fs".
The error for compiled version of 'browser-source-map-support'  is "C.existsSync is not a function"

Looks like 'fs' is defined but not existsSync, I guess the bug is introduced by https://github.com/evanw/node-source-map-support/commit/b19ff7625f631bd8245491edca36b486638423ea#diff-f332e9a051ea7f7b602a3d633c506d30R77

If you run `npm run serve-tests` then go to `http://127.0.0.1:1336/browser-test/` you'll reproduce the issue.

I'll try to see  what I can do to fix it.

**Comment by ardeois** [comment]
Found the issue, here is the fix:
https://github.com/evanw/node-source-map-support/pull/168

@LinusU can you please check if that's ok publish a new version on npm?

Thanks !

**Comment by uiteoi** [comment]
Thanks for the quick fix and 0..4.10 release. The bug is gone for me.

**Comment by ardeois** [comment]
Yes thanks! I confirm it's working for me as well.

**Comment by LinusU** [comment]
🎉 🎉
